### ISSUE TITLE
IP range for SFTP server

### ISSUE THREAD

**Issue by 1234567-abc** [Azure-Samples/sftp-creation-template#9] opened 2020-06-05 17:52 UTC
Hi,

Is there a way to find out the Pubic IP range that is assigned to the ACI FQDN ?

It appears our client has to need to open their firewall each time the IP address changes.

Also, does anyone know what triggers the IP address to change?

Ideally, It would be great to assign a static public IP however researching online it doesn't seem clear if this can be done for an existing ACI and also understand it can be expensive deploy an application gateway

Thanks

**Comment by bhummerstone** [comment] 2020-06-05 21:08
There's a roadmap item to address this scenario: will try and remember to circle back when this is available!

**Comment by bhummerstone** [comment] 2020-08-03 08:50
So looping back on this: the ability to use IP addressess as the backend pool for an Azure Load Balancer in front of was intended to resolve this, but unfortunately ACI isn't supported just yet: https://docs.microsoft.com/en-us/azure/load-balancer/backend-pool-management#configure-backend-pool-by-ip-address-and-virtual-network

**Comment by bhummerstone** [comment] 2021-06-23 13:47
Closing this issue as it has been idle for a while

**Closed as completed by bhummerstone** 2021-06-23 13:47 UTC
