### ISSUE TITLE
IP Changes 

### ISSUE THREAD

**Issue by franksmith5** [Azure-Samples/sftp-creation-template#1] opened 2019-05-09 19:54 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
If the Resrouce Group is restarted the public IP changes. This is preventing us from using it in a PROD environment integrations which rely on SFTP require the same IP each time. Is this possible? 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by cloudioglobal** [comment] 2019-06-04 10:50
Is there a way to get this to assign a FQDN, so that when the container or as mentioned here, the RG is restarted, the public IP address changes? If this had a fix FQDN then SFTP clients could use that and let MS DNS resolve when connecting or stop the IP changing, either way it would result in a production ready offer

**Comment by bhummerstone** [comment] 2019-06-17 11:06
@franksmith5 I don't think you can choose a particular static IP to use, but I will check

**Comment by bhummerstone** [comment] 2019-06-17 11:08
@cloudioglobal you can specify a "dnsNameLabel" property as part of the IP address block to choose a DNS name to be associated; see the template reference here for more info: https://docs.microsoft.com/en-us/azure/templates/Microsoft.ContainerInstance/2018-10-01/containerGroups

You could then create a DNS alias on a custom domain if you wanted to have something more bespoke.

**Comment by bhummerstone** [comment] 2019-06-25 09:07
@franksmith5 I've checked, and you can't currently specify a static IP for the ACI. One way would be to deploy it inside a vNet and put e.g. an Azure Firewall in front of it with a static IP instead.

Otherwise, using the static DNS name would be the best way forward

**Comment by cloudioglobal** [comment] 2019-06-25 09:23
Do you have the code to do the static DNS name or build it into the deployment script?

Kind regards

Gary Hocking
________________________________

**Comment by egondalia** [comment] 2019-06-25 11:07
Hi I too would like to know how to deploy this using a static DNS name, would really appreciate help on this please.  I tried the below but it just failed with a Gateway timeout any help my syntax maybe wrong :(

 "osType": "Linux",
                "ipAddress": {
                    "type": "Public",
                    **"DNS name label": "egege12342",**
                    "ports": [
                        {
                            "protocol": "TCP",
                            "port": 22

Error from Portal
"InvalidRequestContent", "message": "The request content was invalid and could not be deserialized: 'Could not find member 'DNS name label' on object of type 'IpAddress'. Path 'properties.ipAddress.['DNS name label']', line 1, position 433.'." } }

**Comment by bhummerstone** [comment] 2019-06-25 12:34
Sure, try this:

```json
"ipAddress": {
      "ports": [
        {
          "protocol": "TCP",
          "port": 22
        }
      ],
      "type": "Public",
      "dnsNameLabel": "egege12342"
    }
```

**Comment by bhummerstone** [comment] 2019-08-16 12:27
@franksmith5 is it OK to close this issue now?

**Comment by karyjac** [comment] 2019-11-04 21:22
@bhummerstone I tried adding the dnsNameLabel to the code but still deployed without FQDN :(
Any ideas?

**Comment by karyjac** [comment] 2019-12-19 21:55
I have successfully modified the code so a FQDN is assigned, if anyone needs it here it is:
https://github.com/karyjac/sftp-creation-template

**Comment by chicane-S54** [comment] 2020-01-15 18:18
I'm sorry what good is a DNS entry with a FQDN if the IP changes then you have to update the DNS entry...

**Comment by bhummerstone** [comment] 2020-01-16 13:30
@javadevtech the DNS is managed by Microsoft and automatically updates to point to the new IP. You could also alias it if you wanted a custom domain name

**Comment by porrascarlos802018** [comment] 2020-03-17 18:44
@bhummerstone 
by alias you mean to follow this procedure?
https://docs.microsoft.com/en-us/azure/dns/dns-alias

**Comment by macolso** [comment] 2020-03-17 20:46
This tutorial walks you through SFTP set-up using ACI's enabled with FQDN: https://github.com/Azure-Samples/sftp-creation-template/tree/master/

**Comment by bhummerstone** [comment] 2020-03-18 09:24
@porrascarlos802018 yep: CNAME the FQDN for the ACI container group

**Comment by sohilsam** [comment] 2020-05-18 22:25
FQDN is a good option but it does not help when the firewall does not support so static is the only option. Is it possible docker 1.10?

**Comment by bhummerstone** [comment] 2020-05-22 13:49
There are some roadmap items for ACI that could make a static IP possible: I'll try and remember to update this issue when they're released :)

**Comment by varunsampat30** [comment] 2020-11-20 18:16
Hello,

I tried the following demo to implement a static IP address for the SFTP server:
- https://docs.microsoft.com/en-us/azure/container-instances/container-instances-application-gateway

However, I seem to be getting **Backend health issues**. More specifically:

- "Time taken by the backend to respond to application gateway's health probe is more than the time-out threshold in the probe c...." on Azure Portal for the Application Gateway.
- When I directly try to access the Public IP (through Chrome) of the application gateway, I get a **502 Bad Gateway** error. 

Whereas the tutorial is fairly straightforward, my guess is because the ACI is used as a SFTP here, the Application Gateway's rules/listeners have to be configured differently. However, I am not sure if this is the root cause.

Note: my SFTP server works without any issues. I have configured it to accept SSH key pairs or user/passwords and everything is tested on FileZilla. I have not changed the SFTP template to work with the Vnet.

Any help would be appreciated.

Thank you!

**Comment by bhummerstone** [comment] 2020-11-24 10:35
App Gateway requires an HTTP response code on a specific port in order to do the health probe, so won't work for SFTP.

The way I see having a static IP would be using this, although it doesn't support ACI at the moment: https://docs.microsoft.com/en-us/azure/load-balancer/backend-pool-management#configure-backend-pool-by-ip-address-and-virtual-network

**Comment by bhummerstone** [comment] 2021-06-23 13:44
Closing this issue as it has been inactive for a while

**Closed as completed by bhummerstone** 2021-06-23 13:44 UTC
